name: RatInk 
on: 
  push: 
    branches:
      - master
  pull_request: 
      branches: 
        - master 
jobs: 
  test: 
    name: Lint & Run Jest
    runs-on: levan
    strategy:
      matrix:
        node_version: [16] 
    steps: 
      - name: Checkout the Git repository
        uses: actions/checkout@v2 
      - name: Setup Node.js 
        uses: actions/setup-node@v2 
        with: 
          node-version: ${{ matrix.node_version }}
      - name: Install Dependencies / Check if Lint is installed / Check if Jest is installed 
        run: |
          sudo npm install -g yarn
          yarn 
          yarn add eslint 
          yarn add jest 
      - name: Start lint 
        run: 
          yarn eslint 
      - name: Start jest
        run: yarn jest
